### ISSUE TITLE
gpt 3.5 turbo instruct

### ISSUE THREAD

**Issue by Auditormadness9** [NovaOSS/free-ai-apis#22]
Can you please update on which one currently supports the new `GPT 3.5 Turbo Instruct` completion model?

Thanks.

**Comment by Lancelot-24** [comment]
I don’t think any of them at the moment but a few support text-davinci-003 which is fairly similar

**Comment by Auditormadness9** [comment]
Not similar really, it's basically a davinci style uncensored version of
gpt 3.5.

Alrighty, I'll use stock OpenAI until one comes up. Thanks for the update
👍🏼

**Comment by zukixa** [comment]
there really isn't a reliable source of gpt-3.5-turbo-instruct that isn't just using stolen openAI keys, so it may take a while till one pops up, because the ones using keys (webraft, skailar) don't add it due to NSFW/ToS lol
